#!/usr/bin/env python3
"""Causal stability audit for chan.py morphological buy/sell points.

This research-only harness feeds one front-adjusted daily bar at a time into a
pinned checkout of Vespa314/chan.py.  It records when each marker first appears,
when its underlying stroke becomes sure, when the marker crosses the engine's
structural freeze boundary, and whether it disappears beforehand.
Forward outcomes are measured from the *detection* frame (next-day open), never
from the earlier anchor bar that is only known retrospectively.

The script intentionally does not vendor chan.py or raw BaoStock data.  Reuse the
cache and point-in-time cohort generated by kline-signal-backtest.py:

    python scripts/research/chan-signal-stability.py \
      --chan-root /path/to/pinned/chan.py \
      --baseline docs/research-data/kline-signal-backtest-2026-08-21.json \
      --cache-dir /tmp/hanai-kline-backtest-cache \
      --output docs/research-data/chan-signal-stability-2026-08-21.json

The output is an engineering validation artifact, not investment advice or
evidence that the underlying theory is profitable.
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import hashlib
import json
import math
import random
import statistics
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Sequence


BUY_COMMISSION = 0.0003
SELL_COMMISSION = 0.0003
TRANSFER_FEE = 0.00001
SELL_STAMP_DUTY = 0.0005
SLIPPAGE = 0.001
BUY_COST = BUY_COMMISSION + TRANSFER_FEE
SELL_COST = SELL_COMMISSION + TRANSFER_FEE + SELL_STAMP_DUTY
HORIZONS = (5, 10, 20)


@dataclasses.dataclass(frozen=True)
class Bar:
    date: dt.date
    code: str
    open: float
    high: float
    low: float
    close: float
    preclose: float
    volume: float
    amount: float | None
    turnover: float | None
    is_st: bool


@dataclasses.dataclass
class Episode:
    symbol: str
    side: str
    anchor_index: int
    anchor_date: str
    first_seen_index: int
    first_seen_date: str
    initial_state: str
    first_types: list[str]
    observed_types: set[str]
    first_bi_sure_index: int | None = None
    first_bi_sure_date: str | None = None
    bi_sure_types: list[str] | None = None
    first_frozen_index: int | None = None
    first_frozen_date: str | None = None
    frozen_types: list[str] | None = None
    disappeared_index: int | None = None
    disappeared_date: str | None = None
    last_seen_index: int | None = None
    last_seen_date: str | None = None

    @property
    def is_bi_sure(self) -> bool:
        return self.first_bi_sure_index is not None

    @property
    def is_frozen(self) -> bool:
        return self.first_frozen_index is not None

    @property
    def final_state(self) -> str:
        if self.disappeared_index is not None and not self.is_frozen:
            if self.is_bi_sure:
                return "invalidated_after_bi_sure_before_marker_freeze"
            return "invalidated_before_bi_sure"
        if self.disappeared_index is not None and self.is_frozen:
            return "frozen_then_disappeared_invariant_violation"
        if self.is_frozen:
            return "marker_frozen_active"
        if self.is_bi_sure:
            return "bi_sure_but_marker_not_frozen_at_sample_end"
        return "provisional_active_at_sample_end"


@dataclasses.dataclass(frozen=True)
class Observation:
    symbol: str
    side: str
    types: tuple[str, ...]
    stage: str
    decision_index: int
    decision_year: int
    horizon: int
    raw_return: float
    signed_return: float
    net_buy_return: float | None
    executable_next_open: bool


def parse_number(raw: str) -> float | None:
    if raw == "":
        return None
    value = float(raw)
    return value if math.isfinite(value) else None


def load_bars(path: Path) -> list[Bar]:
    rows = json.loads(path.read_text(encoding="utf-8"))
    bars: list[Bar] = []
    for row in rows:
        if len(row) != 12:
            continue
        try:
            numeric = [parse_number(value) for value in row[2:8]]
        except ValueError:
            continue
        if any(value is None for value in numeric):
            continue
        open_price, high, low, close, preclose, volume = (
            float(value) for value in numeric if value is not None
        )
        if min(open_price, high, low, close, preclose) <= 0:
            continue
        bars.append(
            Bar(
                date=dt.date.fromisoformat(row[0]),
                code=row[1],
                open=open_price,
                high=high,
                low=low,
                close=close,
                preclose=preclose,
                volume=volume,
                amount=parse_number(row[8]),
                turnover=parse_number(row[9]),
                is_st=row[11] == "1",
            )
        )
    return bars


def bar_manifest(bars: Sequence[Bar]) -> dict[str, Any]:
    digest = hashlib.sha256()
    for bar in bars:
        digest.update(
            (
                f"{bar.date.isoformat()}|{bar.open:.8f}|{bar.high:.8f}|"
                f"{bar.low:.8f}|{bar.close:.8f}|{bar.volume:.4f}\n"
            ).encode()
        )
    return {
        "rows": len(bars),
        "first_date": bars[0].date.isoformat() if bars else None,
        "last_date": bars[-1].date.isoformat() if bars else None,
        "sha256": digest.hexdigest(),
    }


def cache_path(cache_dir: Path, symbol: str, metadata: dict[str, Any]) -> Path:
    start = metadata["requested_start"]
    end = metadata["requested_end"]
    return cache_dir / f"{symbol.replace('.', '-')}-{start}-{end}-qfq.json"


def git_value(root: Path, *args: str) -> str | None:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), *args], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def percentile(values: Sequence[float], fraction: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    index = max(0, min(len(ordered) - 1, int(fraction * (len(ordered) - 1))))
    return ordered[index]


def median_or_none(values: Iterable[float]) -> float | None:
    materialized = list(values)
    return statistics.median(materialized) if materialized else None


def limit_ratio(bar: Bar) -> float:
    if bar.is_st:
        return 0.05
    code = bar.code.split(".")[-1]
    if code.startswith(("688", "300")):
        return 0.20
    if code.startswith(("8", "4")):
        return 0.30
    return 0.10


def unavailable_at_limit(bar: Bar, side: str) -> bool:
    ratio = limit_ratio(bar)
    tolerance = max(0.01, bar.preclose * 0.0005)
    if side == "buy":
        return bar.open >= bar.preclose * (1 + ratio) - tolerance
    return bar.open <= bar.preclose * (1 - ratio) + tolerance


def make_klu(bar: Bar, api: dict[str, Any]) -> Any:
    fields = api["DATA_FIELD"]
    timestamp = api["CTime"](
        bar.date.year, bar.date.month, bar.date.day, 0, 0
    )
    values: dict[str, Any] = {
        fields.FIELD_TIME: timestamp,
        fields.FIELD_OPEN: bar.open,
        fields.FIELD_HIGH: bar.high,
        fields.FIELD_LOW: bar.low,
        fields.FIELD_CLOSE: bar.close,
        fields.FIELD_VOLUME: bar.volume,
    }
    if bar.amount is not None:
        values[fields.FIELD_TURNOVER] = bar.amount
    if bar.turnover is not None:
        values[fields.FIELD_TURNRATE] = bar.turnover
    return api["CKLine_Unit"](values)


def current_points(chan: Any) -> dict[tuple[str, int], dict[str, Any]]:
    points: dict[tuple[str, int], dict[str, Any]] = {}
    marker_freeze_boundary = chan[0].bs_point_lst.last_sure_pos
    for point in chan.get_latest_bsp(number=0):
        anchor_index = point.bi.get_end_klu().idx
        side = "buy" if point.is_buy else "sell"
        key = (side, anchor_index)
        info = {
            "bi_sure": bool(point.bi.is_sure),
            "marker_frozen": anchor_index <= marker_freeze_boundary,
            "types": sorted({item.value for item in point.type}),
        }
        if key in points:
            points[key]["types"] = sorted(
                set(points[key]["types"]) | set(info["types"])
            )
            points[key]["bi_sure"] = points[key]["bi_sure"] or info["bi_sure"]
            points[key]["marker_frozen"] = (
                points[key]["marker_frozen"] or info["marker_frozen"]
            )
        else:
            points[key] = info
    return points


def run_symbol(
    symbol: str,
    bars: Sequence[Bar],
    analysis_start: dt.date,
    analysis_end: dt.date | None,
    overrides: dict[str, Any],
    api: dict[str, Any],
) -> list[Episode]:
    config_values = {
        "trigger_step": True,
        "print_warning": False,
        "print_err_time": False,
        **overrides,
    }
    config = api["CChanConfig"](dict(config_values))
    level = api["KL_TYPE"].K_DAY
    chan = api["CChan"](code=symbol, lv_list=[level], config=config)

    previous: dict[tuple[str, int], dict[str, Any]] = {}
    active: dict[tuple[str, int], Episode | None] = {}
    episodes: list[Episode] = []

    for frame_index, bar in enumerate(bars):
        if analysis_end is not None and bar.date > analysis_end:
            break
        chan.trigger_load({level: [make_klu(bar, api)]})
        current = current_points(chan)

        if bar.date < analysis_start:
            previous = current
            continue

        previous_keys = set(previous)
        current_keys = set(current)

        for key in sorted(previous_keys - current_keys):
            episode = active.pop(key, None)
            if episode is not None:
                episode.disappeared_index = frame_index
                episode.disappeared_date = bar.date.isoformat()

        for key in sorted(current_keys - previous_keys):
            side, anchor_index = key
            if not 0 <= anchor_index < len(bars):
                continue
            point = current[key]
            episode = Episode(
                symbol=symbol,
                side=side,
                anchor_index=anchor_index,
                anchor_date=bars[anchor_index].date.isoformat(),
                first_seen_index=frame_index,
                first_seen_date=bar.date.isoformat(),
                initial_state=(
                    "marker_frozen"
                    if point["marker_frozen"]
                    else "bi_sure"
                    if point["bi_sure"]
                    else "provisional"
                ),
                first_types=list(point["types"]),
                observed_types=set(point["types"]),
                last_seen_index=frame_index,
                last_seen_date=bar.date.isoformat(),
            )
            if point["bi_sure"]:
                episode.first_bi_sure_index = frame_index
                episode.first_bi_sure_date = bar.date.isoformat()
                episode.bi_sure_types = list(point["types"])
            if point["marker_frozen"]:
                episode.first_frozen_index = frame_index
                episode.first_frozen_date = bar.date.isoformat()
                episode.frozen_types = list(point["types"])
            episodes.append(episode)
            active[key] = episode

        for key in sorted(current_keys & previous_keys):
            point = current[key]
            if key not in active:
                # Point was already present before the out-of-sample start and is
                # therefore left-censored; retain it only to detect its removal.
                active[key] = None
                continue
            episode = active[key]
            if episode is None:
                continue
            episode.observed_types.update(point["types"])
            episode.last_seen_index = frame_index
            episode.last_seen_date = bar.date.isoformat()
            if point["bi_sure"] and not episode.is_bi_sure:
                episode.first_bi_sure_index = frame_index
                episode.first_bi_sure_date = bar.date.isoformat()
                episode.bi_sure_types = list(point["types"])
            if point["marker_frozen"] and not episode.is_frozen:
                episode.first_frozen_index = frame_index
                episode.first_frozen_date = bar.date.isoformat()
                episode.frozen_types = list(point["types"])

        previous = current

    return episodes


def episode_observations(
    episodes: Sequence[Episode], bars_by_symbol: dict[str, list[Bar]]
) -> list[Observation]:
    observations: list[Observation] = []
    for episode in episodes:
        decisions: list[tuple[str, int, Sequence[str]]] = [
            ("first_seen", episode.first_seen_index, episode.first_types)
        ]
        if episode.first_bi_sure_index is not None:
            decisions.append(
                (
                    "underlying_bi_sure",
                    episode.first_bi_sure_index,
                    episode.bi_sure_types or episode.first_types,
                )
            )
        if episode.first_frozen_index is not None:
            decisions.append(
                (
                    "marker_frozen",
                    episode.first_frozen_index,
                    episode.frozen_types or episode.first_types,
                )
            )
        for stage, decision_index, stage_types in decisions:
            bars = bars_by_symbol[episode.symbol]
            entry_index = decision_index + 1
            if entry_index >= len(bars):
                continue
            executable = not unavailable_at_limit(bars[entry_index], episode.side)
            for horizon in HORIZONS:
                target_index = entry_index + horizon
                if target_index >= len(bars):
                    continue
                raw_return = bars[target_index].close / bars[entry_index].open - 1
                signed_return = raw_return if episode.side == "buy" else -raw_return
                net_buy_return: float | None = None
                if episode.side == "buy" and executable:
                    entry_effective = (
                        bars[entry_index].open * (1 + SLIPPAGE) / (1 - BUY_COST)
                    )
                    exit_effective = (
                        bars[target_index].close
                        * (1 - SLIPPAGE)
                        * (1 - SELL_COST)
                    )
                    net_buy_return = exit_effective / entry_effective - 1
                observations.append(
                    Observation(
                        symbol=episode.symbol,
                        side=episode.side,
                        types=tuple(sorted(stage_types)),
                        stage=stage,
                        decision_index=decision_index,
                        decision_year=bars[decision_index].date.year,
                        horizon=horizon,
                        raw_return=raw_return,
                        signed_return=signed_return,
                        net_buy_return=net_buy_return,
                        executable_next_open=executable,
                    )
                )
    return observations


def cluster_bootstrap(
    observations: Sequence[Observation], seed: int, iterations: int = 2000
) -> dict[str, list[float] | None]:
    grouped: dict[str, list[Observation]] = defaultdict(list)
    for observation in observations:
        grouped[observation.symbol].append(observation)
    symbols = sorted(grouped)
    if not symbols:
        return {"direction_correct_95ci": None, "mean_signed_return_95ci": None}
    rng = random.Random(seed)
    correct_rates: list[float] = []
    means: list[float] = []
    net_buy_positive_rates: list[float] = []
    net_buy_means: list[float] = []
    for _ in range(iterations):
        sampled: list[Observation] = []
        for _ in symbols:
            sampled.extend(grouped[rng.choice(symbols)])
        signed = [item.signed_return for item in sampled]
        correct_rates.append(sum(value > 0 for value in signed) / len(signed))
        means.append(statistics.fmean(signed))
        net_buys = [
            item.net_buy_return
            for item in sampled
            if item.net_buy_return is not None
        ]
        if net_buys:
            net_buy_positive_rates.append(
                sum(value > 0 for value in net_buys) / len(net_buys)
            )
            net_buy_means.append(statistics.fmean(net_buys))
    return {
        "direction_correct_95ci": [
            percentile(correct_rates, 0.025),
            percentile(correct_rates, 0.975),
        ],
        "mean_signed_return_95ci": [
            percentile(means, 0.025),
            percentile(means, 0.975),
        ],
        "net_buy_positive_rate_95ci": (
            [
                percentile(net_buy_positive_rates, 0.025),
                percentile(net_buy_positive_rates, 0.975),
            ]
            if net_buy_positive_rates
            else None
        ),
        "mean_net_buy_return_95ci": (
            [
                percentile(net_buy_means, 0.025),
                percentile(net_buy_means, 0.975),
            ]
            if net_buy_means
            else None
        ),
    }


def horizon_cooldown(
    observations: Sequence[Observation], bars: int
) -> list[Observation]:
    """Keep one actionable marker per symbol/side during a holding horizon."""
    selected: list[Observation] = []
    last_decision: dict[tuple[str, str], int] = {}
    for observation in sorted(
        observations,
        key=lambda item: (item.decision_index, item.symbol, item.side, item.types),
    ):
        key = (observation.symbol, observation.side)
        previous = last_decision.get(key)
        if previous is not None and observation.decision_index <= previous + bars:
            continue
        selected.append(observation)
        last_decision[key] = observation.decision_index
    return selected


def brief_outcome_stats(observations: Sequence[Observation]) -> dict[str, Any]:
    signed = [item.signed_return for item in observations]
    net_buys = [
        item.net_buy_return
        for item in observations
        if item.net_buy_return is not None
    ]
    return {
        "signals": len(observations),
        "symbols": len({item.symbol for item in observations}),
        "direction_correct_rate": (
            sum(value > 0 for value in signed) / len(signed) if signed else None
        ),
        "mean_signed_return": statistics.fmean(signed) if signed else None,
        "net_buy_positive_rate": (
            sum(value > 0 for value in net_buys) / len(net_buys)
            if net_buys
            else None
        ),
        "mean_net_buy_return": statistics.fmean(net_buys) if net_buys else None,
    }


def yearly_outcome_stats(observations: Sequence[Observation]) -> dict[str, Any]:
    return {
        str(year): brief_outcome_stats(
            [item for item in observations if item.decision_year == year]
        )
        for year in sorted({item.decision_year for item in observations})
    }


def outcome_summary(
    observations: Sequence[Observation], seed_prefix: str
) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for stage in ("first_seen", "underlying_bi_sure", "marker_frozen"):
        result[stage] = {}
        for horizon in HORIZONS:
            selected = [
                item
                for item in observations
                if item.stage == stage and item.horizon == horizon
            ]
            signed = [item.signed_return for item in selected]
            buys = [item for item in selected if item.side == "buy"]
            sells = [item for item in selected if item.side == "sell"]
            net_buys = [
                item.net_buy_return
                for item in buys
                if item.net_buy_return is not None
            ]
            seed = int.from_bytes(
                hashlib.sha256(
                    f"{seed_prefix}|{stage}|{horizon}".encode()
                ).digest()[:8],
                "big",
            )
            cooldown = horizon_cooldown(selected, horizon)
            result[stage][str(horizon)] = {
                "signals": len(selected),
                "symbols": len({item.symbol for item in selected}),
                "buy_signals": len(buys),
                "sell_signals": len(sells),
                "next_open_unexecutable": sum(
                    not item.executable_next_open for item in selected
                ),
                "direction_correct_rate": (
                    sum(value > 0 for value in signed) / len(signed) if signed else None
                ),
                "mean_signed_return": statistics.fmean(signed) if signed else None,
                "median_signed_return": statistics.median(signed) if signed else None,
                "buy_positive_rate_raw": (
                    sum(item.raw_return > 0 for item in buys) / len(buys)
                    if buys
                    else None
                ),
                "sell_avoided_decline_rate_raw": (
                    sum(item.raw_return < 0 for item in sells) / len(sells)
                    if sells
                    else None
                ),
                "buy_positive_rate_after_costs": (
                    sum(value > 0 for value in net_buys) / len(net_buys)
                    if net_buys
                    else None
                ),
                "mean_buy_return_after_costs": (
                    statistics.fmean(net_buys) if net_buys else None
                ),
                "cluster_bootstrap": cluster_bootstrap(selected, seed),
                "by_decision_year": yearly_outcome_stats(selected),
                "non_overlapping_horizon_cooldown": {
                    **brief_outcome_stats(cooldown),
                    "by_decision_year": yearly_outcome_stats(cooldown),
                    "cluster_bootstrap": cluster_bootstrap(
                        cooldown, seed ^ 0xC001D00D, iterations=1000
                    ),
                },
            }
        type_breakdown: dict[str, Any] = {}
        for horizon in HORIZONS:
            stage_observations = [
                item
                for item in observations
                if item.stage == stage and item.horizon == horizon
            ]
            labels = sorted(
                {
                    f"{item.side}:{signal_type}"
                    for item in stage_observations
                    for signal_type in item.types
                }
            )
            type_breakdown[str(horizon)] = {}
            for label in labels:
                side, signal_type = label.split(":", 1)
                selected = [
                    item
                    for item in stage_observations
                    if item.side == side and signal_type in item.types
                ]
                signed = [item.signed_return for item in selected]
                net_buys = [
                    item.net_buy_return
                    for item in selected
                    if item.net_buy_return is not None
                ]
                type_seed = int.from_bytes(
                    hashlib.sha256(
                        f"{seed_prefix}|{stage}|{horizon}|{label}".encode()
                    ).digest()[:8],
                    "big",
                )
                cooldown = horizon_cooldown(selected, horizon)
                type_breakdown[str(horizon)][label] = {
                    "signals": len(selected),
                    "symbols": len({item.symbol for item in selected}),
                    "direction_correct_rate": (
                        sum(value > 0 for value in signed) / len(signed)
                        if signed
                        else None
                    ),
                    "mean_signed_return": (
                        statistics.fmean(signed) if signed else None
                    ),
                    "positive_rate_after_costs_if_buy": (
                        sum(value > 0 for value in net_buys) / len(net_buys)
                        if net_buys
                        else None
                    ),
                    "by_decision_year": yearly_outcome_stats(selected),
                    "non_overlapping_horizon_cooldown": {
                        **brief_outcome_stats(cooldown),
                        "by_decision_year": yearly_outcome_stats(cooldown),
                        "cluster_bootstrap": cluster_bootstrap(
                            cooldown, type_seed ^ 0xC001D00D, iterations=1000
                        ),
                    },
                    "cluster_bootstrap": cluster_bootstrap(
                        selected,
                        type_seed,
                        iterations=1000,
                    ),
                }
        result[stage]["by_side_and_type_non_exclusive"] = type_breakdown
    return result


def lifecycle_summary(episodes: Sequence[Episode]) -> dict[str, Any]:
    initially_provisional = [
        episode for episode in episodes if episode.initial_state == "provisional"
    ]
    bi_sure = [episode for episode in episodes if episode.is_bi_sure]
    frozen = [episode for episode in episodes if episode.is_frozen]
    states = Counter(episode.final_state for episode in episodes)
    sides = Counter(episode.side for episode in episodes)
    types = Counter(
        f"{episode.side}:{signal_type}"
        for episode in episodes
        for signal_type in episode.observed_types
    )
    provisional_invalidated_before_bi_sure = [
        episode
        for episode in initially_provisional
        if episode.final_state == "invalidated_before_bi_sure"
    ]
    provisional_bi_sure = [
        episode for episode in initially_provisional if episode.is_bi_sure
    ]
    provisional_frozen = [
        episode for episode in initially_provisional if episode.is_frozen
    ]
    return {
        "episodes": len(episodes),
        "symbols": len({episode.symbol for episode in episodes}),
        "by_side": dict(sorted(sides.items())),
        "by_side_and_type": dict(sorted(types.items())),
        "by_final_state": dict(sorted(states.items())),
        "initially_provisional": len(initially_provisional),
        "initially_bi_sure_or_frozen_backfilled": sum(
            episode.initial_state != "provisional" for episode in episodes
        ),
        "provisional_underlying_bi_sure_rate": (
            len(provisional_bi_sure) / len(initially_provisional)
            if initially_provisional
            else None
        ),
        "provisional_marker_freeze_rate": (
            len(provisional_frozen) / len(initially_provisional)
            if initially_provisional
            else None
        ),
        "provisional_invalidation_before_bi_sure_rate": (
            len(provisional_invalidated_before_bi_sure) / len(initially_provisional)
            if initially_provisional
            else None
        ),
        "bi_sure_marker_later_invalidated": states.get(
            "invalidated_after_bi_sure_before_marker_freeze", 0
        ),
        "frozen_marker_disappearance_invariant_violations": states.get(
            "frozen_then_disappeared_invariant_violation", 0
        ),
        "median_first_detection_lag_bars_from_anchor": median_or_none(
            episode.first_seen_index - episode.anchor_index for episode in episodes
        ),
        "median_underlying_bi_sure_lag_bars_from_anchor": median_or_none(
            episode.first_bi_sure_index - episode.anchor_index
            for episode in bi_sure
            if episode.first_bi_sure_index is not None
        ),
        "median_marker_freeze_lag_bars_from_anchor": median_or_none(
            episode.first_frozen_index - episode.anchor_index
            for episode in frozen
            if episode.first_frozen_index is not None
        ),
        "median_wait_from_first_seen_to_bi_sure_bars": median_or_none(
            episode.first_bi_sure_index - episode.first_seen_index
            for episode in bi_sure
            if episode.first_bi_sure_index is not None
        ),
        "median_wait_from_first_seen_to_marker_freeze_bars": median_or_none(
            episode.first_frozen_index - episode.first_seen_index
            for episode in frozen
            if episode.first_frozen_index is not None
        ),
    }


def baseline_outcomes(
    bars_by_symbol: dict[str, list[Bar]],
    analysis_start: dt.date,
    analysis_end: dt.date | None,
) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for horizon in HORIZONS:
        returns: list[float] = []
        for bars in bars_by_symbol.values():
            for decision_index, bar in enumerate(bars):
                if bar.date < analysis_start:
                    continue
                if analysis_end is not None and bar.date > analysis_end:
                    continue
                entry_index = decision_index + 1
                target_index = entry_index + horizon
                if target_index >= len(bars):
                    continue
                returns.append(bars[target_index].close / bars[entry_index].open - 1)
        result[str(horizon)] = {
            "samples": len(returns),
            "positive_rate": sum(value > 0 for value in returns) / len(returns),
            "decline_rate": sum(value < 0 for value in returns) / len(returns),
            "mean_return": statistics.fmean(returns),
            "median_return": statistics.median(returns),
        }
    return result


def serialized_episode(
    episode: Episode, bars_by_symbol: dict[str, list[Bar]]
) -> dict[str, Any]:
    return {
        "symbol": episode.symbol,
        "side": episode.side,
        "anchor_date": episode.anchor_date,
        "first_seen_date": episode.first_seen_date,
        "first_underlying_bi_sure_date": episode.first_bi_sure_date,
        "first_marker_frozen_date": episode.first_frozen_date,
        "disappeared_date": episode.disappeared_date,
        "initial_state": episode.initial_state,
        "final_state": episode.final_state,
        "types": sorted(episode.observed_types),
        "first_seen_types": episode.first_types,
        "underlying_bi_sure_types": episode.bi_sure_types,
        "marker_frozen_types": episode.frozen_types,
        "detection_lag_bars": episode.first_seen_index - episode.anchor_index,
        "underlying_bi_sure_lag_bars": (
            episode.first_bi_sure_index - episode.anchor_index
            if episode.first_bi_sure_index is not None
            else None
        ),
        "marker_freeze_lag_bars": (
            episode.first_frozen_index - episode.anchor_index
            if episode.first_frozen_index is not None
            else None
        ),
        "wait_to_underlying_bi_sure_bars": (
            episode.first_bi_sure_index - episode.first_seen_index
            if episode.first_bi_sure_index is not None
            else None
        ),
        "wait_to_marker_freeze_bars": (
            episode.first_frozen_index - episode.first_seen_index
            if episode.first_frozen_index is not None
            else None
        ),
        "anchor_close": bars_by_symbol[episode.symbol][episode.anchor_index].close,
    }


def round_floats(value: Any) -> Any:
    if isinstance(value, float):
        return round(value, 8) if math.isfinite(value) else None
    if isinstance(value, dict):
        return {key: round_floats(item) for key, item in value.items()}
    if isinstance(value, list):
        return [round_floats(item) for item in value]
    return value


def compact_episode_ledger(
    episodes: Sequence[Episode], bars_by_symbol: dict[str, list[Bar]]
) -> tuple[str, list[dict[str, Any]]]:
    ledger = [serialized_episode(episode, bars_by_symbol) for episode in episodes]
    canonical = json.dumps(
        ledger, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode()
    examples: list[dict[str, Any]] = []
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in ledger:
        grouped[item["final_state"]].append(item)
    for state in sorted(grouped):
        ordered = sorted(
            grouped[state],
            key=lambda item: (
                item["first_seen_date"], item["symbol"], item["anchor_date"]
            ),
        )
        examples.extend(ordered[:5])
        examples.extend(ordered[-5:])
    deduplicated: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for item in examples:
        key = (
            item["symbol"],
            item["side"],
            item["anchor_date"],
            item["first_seen_date"],
        )
        deduplicated[key] = item
    return hashlib.sha256(canonical).hexdigest(), list(deduplicated.values())


def import_chan(root: Path) -> dict[str, Any]:
    if not (root / "Chan.py").exists():
        raise SystemExit(f"chan.py checkout not found: {root}")
    sys.path.insert(0, str(root))
    from Chan import CChan  # type: ignore[import-not-found]
    from ChanConfig import CChanConfig  # type: ignore[import-not-found]
    from Common.CEnum import DATA_FIELD, KL_TYPE  # type: ignore[import-not-found]
    from Common.CTime import CTime  # type: ignore[import-not-found]
    from KLine.KLine_Unit import CKLine_Unit  # type: ignore[import-not-found]

    return {
        "CChan": CChan,
        "CChanConfig": CChanConfig,
        "DATA_FIELD": DATA_FIELD,
        "KL_TYPE": KL_TYPE,
        "CTime": CTime,
        "CKLine_Unit": CKLine_Unit,
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    baseline = json.loads(args.baseline.read_text(encoding="utf-8"))
    cohort = baseline["cohorts"][args.cohort]
    analysis_start = dt.date.fromisoformat(cohort["snapshot"])
    analysis_end = (
        dt.date.fromisoformat(args.analysis_end) if args.analysis_end else None
    )
    symbols: list[str] = cohort["symbols"]
    metadata = baseline["metadata"]

    bars_by_symbol: dict[str, list[Bar]] = {}
    manifests: dict[str, Any] = {}
    for symbol in symbols:
        path = cache_path(args.cache_dir, symbol, metadata)
        if not path.exists():
            raise SystemExit(f"missing cached bars: {path}")
        bars = load_bars(path)
        manifest = bar_manifest(bars)
        expected = baseline["universe"][symbol]
        if manifest["sha256"] != expected["sha256"]:
            raise SystemExit(
                f"cache checksum mismatch for {symbol}: "
                f"{manifest['sha256']} != {expected['sha256']}"
            )
        bars_by_symbol[symbol] = bars
        manifests[symbol] = manifest

    api = import_chan(args.chan_root)
    configurations = {
        "official_default_daily_morphology": {},
        "strict_divergence_0_9": {
            "divergence_rate": 0.9,
            "strict_bsp3": True,
            "bsp3_peak": True,
        },
        "independent_relaxed": {
            "min_zs_cnt": 0,
            "bsp1_only_multibi_zs": False,
            "bs1_peak": False,
            "bsp2_follow_1": False,
            "bsp3_follow_1": False,
            "strict_bsp3": False,
        },
    }
    requested_configurations = {
        item.strip() for item in args.configurations.split(",") if item.strip()
    }
    unknown = requested_configurations - set(configurations)
    if unknown:
        raise SystemExit(f"unknown configurations: {sorted(unknown)}")
    configurations = {
        name: overrides
        for name, overrides in configurations.items()
        if name in requested_configurations
    }

    config_results: dict[str, Any] = {}
    anchor_sets: dict[str, set[tuple[str, str, str]]] = {}
    for name, overrides in configurations.items():
        episodes: list[Episode] = []
        for index, symbol in enumerate(symbols, start=1):
            print(
                f"[{name}] {index:02d}/{len(symbols)} {symbol}",
                file=sys.stderr,
                flush=True,
            )
            episodes.extend(
                run_symbol(
                    symbol,
                    bars_by_symbol[symbol],
                    analysis_start,
                    analysis_end,
                    overrides,
                    api,
                )
            )
        observations = episode_observations(episodes, bars_by_symbol)
        anchors = {
            (episode.symbol, episode.side, episode.anchor_date)
            for episode in episodes
        }
        anchor_sets[name] = anchors
        ledger_sha256, episode_examples = compact_episode_ledger(
            episodes, bars_by_symbol
        )
        config_results[name] = {
            "overrides": overrides,
            "lifecycle": lifecycle_summary(episodes),
            "outcomes": outcome_summary(observations, name),
            "episode_ledger_sha256": ledger_sha256,
            "episode_examples": episode_examples,
        }

    overlap: dict[str, Any] = {}
    names = list(configurations)
    for left_index, left in enumerate(names):
        for right in names[left_index + 1 :]:
            intersection = anchor_sets[left] & anchor_sets[right]
            union = anchor_sets[left] | anchor_sets[right]
            overlap[f"{left}__vs__{right}"] = {
                "left_unique_anchors": len(anchor_sets[left]),
                "right_unique_anchors": len(anchor_sets[right]),
                "intersection": len(intersection),
                "jaccard": len(intersection) / len(union) if union else None,
            }

    license_path = args.chan_root / "LICENSE"
    remote = git_value(args.chan_root, "remote", "get-url", "origin")
    return round_floats(
        {
            "metadata": {
                "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
                "purpose": "causal stability audit, not a production strategy",
                "engine": "Vespa314/chan.py",
                "engine_remote": remote,
                "engine_commit": git_value(args.chan_root, "rev-parse", "HEAD"),
                "engine_license": "MIT",
                "engine_license_sha256": (
                    hashlib.sha256(license_path.read_bytes()).hexdigest()
                    if license_path.exists()
                    else None
                ),
                "frequency": "daily only",
                "adjustment": metadata["adjustment"],
                "provider": metadata["provider"],
                "cohort": args.cohort,
                "cohort_snapshot": cohort["snapshot"],
                "analysis_end": analysis_end.isoformat() if analysis_end else None,
                "symbols": len(symbols),
                "requested_start": metadata["requested_start"],
                "requested_end": metadata["requested_end"],
                "decision_rule": (
                    "record at first appearance/underlying-bi-sure/marker-freeze; evaluate from next open; "
                    "never score from the retroactive anchor date"
                ),
                "limitations": [
                    "Daily-only morphology is not a complete multi-level Chan trading strategy.",
                    "A marker is the open-source author's implementation and parameterization, not a canonical truth.",
                    "Point-in-time CSI 300/500 sampling reduces but does not eliminate selection bias.",
                    "Daily OHLCV cannot establish intraday path, queue position, or limit-board executability.",
                ],
                "cost_model_for_buy_forward_returns": metadata["cost_model"],
            },
            "data_manifest": manifests,
            "unconditional_direction_baseline": baseline_outcomes(
                bars_by_symbol, analysis_start, analysis_end
            ),
            "parameter_overlap": overlap,
            "configurations": config_results,
        }
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chan-root", type=Path, required=True)
    parser.add_argument(
        "--baseline",
        type=Path,
        default=Path(
            "docs/research-data/kline-signal-backtest-2026-08-21.json"
        ),
    )
    parser.add_argument(
        "--cache-dir", type=Path, default=Path("/tmp/hanai-kline-backtest-cache")
    )
    parser.add_argument("--cohort", default="2024")
    parser.add_argument(
        "--analysis-end",
        help="Optional inclusive decision-date cutoff (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--configurations",
        default=(
            "official_default_daily_morphology,strict_divergence_0_9,"
            "independent_relaxed"
        ),
        help="Comma-separated configuration names.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "docs/research-data/chan-signal-stability-2026-08-21.json"
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = run(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(args.output)


if __name__ == "__main__":
    main()
